# CS Elettra configuration (python), I.M., 03.2026
# Step 5: add injection jitter errors

error_table:

  magnet_dx:                  30.0e-6
  magnet_dy:                  30.0e-6
  magnet_roll:                50.0e-6

  dipole_dx:                  50.0e-6
  dipole_dy:                  50.0e-6
  dipole_roll:                100.0e-6

  bpm_dx:                     150.0e-6
  bpm_dy:                     150.0e-6
  bpm_roll:                   150.0e-6
  bpm_calibration:            1.0e-2
  bpm_orbit_noise:            1.0e-6
  bpm_tbt_noise:              50.0e-6


parameters:
  corrector_x_max:            8.0e-4
  corrector_y_max:            5.0e-4


injection:
  x:                          0.0
  px:                         0.0
  y:                          0.0
  py:                         0.0
  tau:                        0.0
  delta:                      0.0
  x_error_syst:               2.0e-4
  px_error_syst:              1.5e-4
  y_error_syst:               2.0e-4
  py_error_syst:              1.0e-4
  tau_error_syst:             0.0
  delta_error_syst:           1.0e-3
  x_error_stat:               5.0e-5
  px_error_stat:              5.0e-6
  y_error_stat:               5.0e-6
  py_error_stat:              2.0e-6
  tau_error_stat:             1.67e-4
  delta_error_stat:           1.0e-4
  emit_x:                     140.0e-9
  emit_y:                     14.0e-9
  bunch_length:               2.5e-3
  energy_spread:              1.0e-3
  n_particles:                1


lattice:
  lattice_file:               phase1_lattice.mat
  simulator:                  at
  use:                        RING


magnets:

  bend:
    regex: ^B_
    components:
      - B1L: null
    dx: dipole_dx
    dy: dipole_dy
    roll: dipole_roll

  corr:
    regex: ^CH|^CV
    components:
      - B1L: null
      - A1L: null
    limits:
      - B1L: corrector_x_max
      - A1L: corrector_y_max

  corr_fast:
    regex: ^CFH|^CFV
    components:
      - B1L: null
      - A1L: null
    limits:
      - B1L: corrector_x_max
      - A1L: corrector_y_max

  quad:
    regex: ^QD|^QF|^QAB
    components:
      - B2L: null
    dx: magnet_dx
    dy: magnet_dy
    roll: magnet_roll

  sext:
    regex: ^SF_.*\.(02|03|04|05)$
    components:
      - B3L: null
    dx: magnet_dx
    dy: magnet_dy
    roll: magnet_roll

  sext_corr:
    regex: ^SF_.*\.(01|06)$|^SD_.*\.(01|02|03|04|07|08|09|10)$|^SH_.*\.(01|04)$
    components:
      - B1L: null
      - A1L: null
      - B3L: null
    limits:
      - B1L: corrector_x_max
      - A1L: corrector_y_max
    dx: magnet_dx
    dy: magnet_dy
    roll: magnet_roll

  sext_skew:
    regex: ^SD_.*\.(05|06)$|^SH_.*\.(02|03)$
    components:
      - A2L: null
      - B3L: null
    dx: magnet_dx
    dy: magnet_dy
    roll: magnet_roll

  octu_corr:
    regex: ^OCT_.*\.(01|04)$
    components:
      - B1L: null
      - A1L: null
      - B2L: null
      - B4L: null
    limits:
      - B1L: corrector_x_max
      - A1L: corrector_y_max
    dx: magnet_dx
    dy: magnet_dy
    roll: magnet_roll

  octu_quad:
    regex: ^OCT_.*\.(02|03)$
    components:
      - B2L: null
      - B4L: null
    dx: magnet_dx
    dy: magnet_dy
    roll: magnet_roll


rf:
  main:
    regex: RF
    voltage: null
    phase: null
    frequency: null


bpms:
  bpms:
    regex: ^BPM
    calibration_error: bpm_calibration
    orbit_noise: bpm_orbit_noise
    tbt_noise: bpm_tbt_noise
    dx: bpm_dx
    dy: bpm_dy
    roll: bpm_roll


tuning:

  HCORR:
    - corr: B1L
    - sext_corr: B1L
    - octu_corr: B1L

  VCORR:
    - corr: A1L
    - sext_corr: A1L
    - octu_corr: A1L

  model_RM_folder: ./data

  multipoles:
    - octu_corr: B4L
    - octu_quad: B4L
    - sext_corr: B3L
    - sext: B3L
    - sext_skew: B3L

  bba_magnets:
    - quad: B2L

  tune:
    controls_1:
      regex: ^QD_S.*\.0[23]$
      component: B2L
    controls_2:
      regex: ^QF_S.*\.0[14]$
      component: B2L

  c_minus:
    controls:
      - sext_skew: A2L